name: Publish Zenodo deposit

on:
  push:
    tags: ["v*"]

permissions:
  contents: write

jobs:
  publish:
    uses: impact-scholars/isp-actions-config/.github/workflows/publish-zenodo.yml@feat/zenodo-publish
    with:
      tag: ${{ github.ref_name }}
    secrets:
      ZENODO_TOKEN_SANDBOX: ${{ secrets.ZENODO_TOKEN_SANDBOX }}
